// ui/src/App.jsx
import styles from './App.module.css';
import { createEffect, createSignal } from 'solid-js';
import TimeSection from './TimeSection';
import { invoke } from '@tauri-apps/api/tauri'

function App() {
  let getHour;
  let getMinute;
  let [settings, setSettings] = createSignal({
    autorun: false,
    shutdownTime: "加载中",
  });

  function getSettings() {
    createEffect(() => {
      invoke("get_settings").then((resp) => setSettings(resp));
    })
  }
  getSettings();

  async function setShutdown() {
    await invoke("set_shutdown", { hour: getHour(), minute: getMinute() });
    getSettings();
  }

  async function toggleAutorun() {
    let enable = !settings().autorun;
    await invoke("toggle_autorun", { enable });
    getSettings();
  }

  return (
    <>
      <div>
        <label class="form-switch">
          <input type="checkbox" checked={settings().autorun} onclick={toggleAutorun} />
          <i class="form-icon"></i>开机自启动
        </label>
      </div>
      <div>下次关机时间：{settings().shutdownTime}
      </div>

      <div>
        <label>设置关机时间：</label>
        <TimeSection min={0} max={23} init={0} bind={(getter) => getHour = getter} label="时" />
        <TimeSection min={0} max={59} init={0} bind={(getter) => getMinute = getter} label="分" />
        <button class='btn' onclick={setShutdown}>设定</button>
      </div>
    </>
  );
}

export default App;

// ui-src/src/App.svelte
<script>
	import NumberInput from "./widgets/NumberInput.svelte";
	let window = Window.this;
	let settings = window.xcall("get_settings");
	let shutdownHour = 0;
	let shutdownMinute = 0;
	let autorun = settings.autorun;

	function setAutorun() {
		if (!window.xcall("autorun_when_boot", autorun)) {
			autorun = !autorun;
		}
	}

	function setShutdownTime() {
		window.xcall("set_shutdown", shutdownHour, shutdownMinute);
	}

	window.on("statechange", function () {
		settings = window.xcall("get_settings");
	});
</script>

<main>
	<input
		type="checkbox"
		id="autorun"
		on:click={setAutorun}
		bind:checked={autorun}
	/><label for="autorun">开机自启动</label>
	<div>下次关机时间： {settings.shutdownTime}</div>
	<table>
		<tbody>
			<tr>
				<td>设置关机时间:</td>
				<td>
					<div>
						<NumberInput
							min="0"
							max="23"
							label="时"
							bind:value={shutdownHour}
						/>
						<NumberInput
							min="0"
							max="59"
							label="分"
							bind:value={shutdownMinute}
						/>
					</div>
				</td>
				<td>
					<button on:click={setShutdownTime}>设定</button>
				</td>
			</tr>
		</tbody>
	</table>
</main>
